webtalk_init -webtalk_dir /home/commit/RISC_V/verilog_test/matbi/01_VerilogHDL/chapter_14_power_of_8/xsim.dir/tb_power_of_8/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Feb 25 21:18:12 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212130015_0_0_600" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f4e7efb9-4c7c-4ed7-bddd-f478b481c396" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a9875485-461b-4a17-bf6f-c1e24c679e96" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8600 CPU @ 3.10GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3096.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "2" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "wave_" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "18 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "2 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "16" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "1.26_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "145912_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2644416335 -regid "212130015_0_0_600" -xml /home/commit/RISC_V/verilog_test/matbi/01_VerilogHDL/chapter_14_power_of_8/xsim.dir/tb_power_of_8/webtalk/usage_statistics_ext_xsim.xml -html /home/commit/RISC_V/verilog_test/matbi/01_VerilogHDL/chapter_14_power_of_8/xsim.dir/tb_power_of_8/webtalk/usage_statistics_ext_xsim.html -wdm /home/commit/RISC_V/verilog_test/matbi/01_VerilogHDL/chapter_14_power_of_8/xsim.dir/tb_power_of_8/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
