#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Feb 25 20:10:20 KST 2021
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tb_counter_100_behav -key {Behavioral:sim_1:Functional:tb_counter_100} -tclbatch tb_counter_100.tcl -log simulate.log"
xsim tb_counter_100_behav -key {Behavioral:sim_1:Functional:tb_counter_100} -tclbatch tb_counter_100.tcl -log simulate.log

